services:
  reth:
    image: ghcr.io/paradigmxyz/reth
    pull_policy: always
    container_name: reth
    restart: unless-stopped
    volumes:
      - /mnt/data/eth/sepolia/reth:/reth
      - /secrets/jwtsecret:/reth/jwtsecret
    command: >
      node 
      --chain sepolia
      --datadir /reth
      --log.file.directory /reth/logs
      --metrics reth:9001 
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --http
      --http.addr 0.0.0.0
      --http.api all
      --authrpc.jwtsecret /reth/jwtsecret
    ports:
      - '8545:8545' #http rpc port
      - '9001:9001' #metrics port
      - '8551:8551' #engine api port

  lighthouse:
    image: sigp/lighthouse:latest
    pull_policy: always
    container_name: lighthouse
    restart: unless-stopped
    depends_on:
      - reth
    volumes:
      - /mnt/data/eth/sepolia/lighthouse:/lighthouse
      - /secrets/jwtsecret:/reth/jwtsecret
    command: > 
      lighthouse
      beacon_node
      --network sepolia
      --datadir /lighthouse
      --http
      --http-address=0.0.0.0
      --checkpoint-sync-url https://checkpoint-sync.sepolia.ethpandaops.io
      --metrics
      --metrics-address=0.0.0.0
      --execution-endpoint=http://reth:8551
      --execution-jwt /reth/jwtsecret
      --disable-deposit-contract-sync
      --validator-monitor-auto
    ports:
      - "9000:9000/udp"  # p2p port (udp)
      - "9000:9000/tcp"  # p2p port (tcp)
      - "5052:5052/tcp"  # http rpc port
      - "5054:5054/tcp"  # metrics port

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: root
    restart: unless-stopped
    depends_on:
      - reth
      - lighthouse
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheusdata:/prometheusdata
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheusdata'

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: '472'
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3334:3000
    volumes:
      - grafanadata:/var/lib/grafanadata
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Admin"

volumes:
  prometheusdata:
    driver: local
  grafanadata:
    driver: local
