{
 "title": "Reth Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_network_connected_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stage checkpoints",
   "type": "bargauge",
   "description": "The checkpoints mark the last block a stage can recover from in the case of a crash or shutdown of the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "reth_sync_checkpoint", "legendFormat": "{{stage}}" }
   ]
  },
  {
   "title": "Sync progress (stage progress in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_sync_entities_processed / reth_sync_entities_total",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress as highest block number reached)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "reth_sync_checkpoint", "legendFormat": "{{stage}}" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average commit time",
   "type": "timeseries",
   "description": "The average commit time for database transactions. Generally, this should not be a limiting factor in syncing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_tx_commit_sum[$__rate_interval]) / rate(reth_tx_commit_count[$__rate_interval])",
     "legendFormat": "Commit time"
    }
   ]
  },
  {
   "title": "Commit time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(reth_tx_commit[$__interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Database tables",
   "type": "piechart",
   "description": "The size of tables in the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_db_table_size", "legendFormat": "{{table}}" }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "description": "The size of the database over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_db_table_size )",
     "legendFormat": "Size ({{job}})"
    }
   ]
  },
  {
   "title": "Database pages",
   "type": "piechart",
   "description": "The type of the pages in the database:\n\n- **Leaf** pages contain KV pairs.\n- **Branch** pages contain information about keys in the leaf pages\n- **Overflow** pages store large values and should generally be avoided if possible",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) ( reth_db_table_pages )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overflow pages by table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sort_desc(reth_db_table_pages{type=\"overflow\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stage: Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Gas processed",
   "type": "timeseries",
   "description": "The amount of gas processed by the execution stage in millions per second.\n\nNote: For mainnet, the block range 2,383,397-2,620,384 will be slow because of the 2016 DoS attack.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Mgas/s" } },
   "targets": [
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total[30s])",
     "legendFormat": "Gas/s (30s)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total[1m])",
     "legendFormat": "Gas/s (1m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total[5m])",
     "legendFormat": "Gas/s (5m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total[10m])",
     "legendFormat": "Gas/s (10m)"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "description": "The number of tracked peers in the discovery modules (dnsdisc and discv4)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    { "expr": "reth_network_tracked_peers", "legendFormat": "Tracked peers" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of incoming and outgoing connections, as well as the number of peers we are currently connected to. Outgoing and incoming connections also count peers we are trying to connect to.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "reth_network_incoming_connections",
     "legendFormat": "Incoming connections"
    },
    { "expr": "reth_network_connected_peers", "legendFormat": "Connected peers" }
   ]
  },
  {
   "title": "P2P errors",
   "type": "timeseries",
   "description": "Internal errors in the P2P module. These are expected to happen from time to time. High error rates should not cause alarm if the node is peering otherwise.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "reth_p2pstream_disconnected_errors",
     "legendFormat": "P2P stream disconnected"
    },
    {
     "expr": "reth_network_pending_session_failures",
     "legendFormat": "Failed pending sessions"
    },
    {
     "expr": "reth_network_invalid_messages_received",
     "legendFormat": "Invalid messages"
    }
   ]
  },
  {
   "title": "Peer disconnect reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reth_network_useless_peer", "legendFormat": "UselessPeer" },
    {
     "expr": "reth_network_subprotocol_specific",
     "legendFormat": "SubprotocolSpecific"
    },
    { "expr": "reth_network_already_connected", "legendFormat": "AlreadyConnected" },
    { "expr": "reth_network_client_quitting", "legendFormat": "ClientQuitting" },
    {
     "expr": "reth_network_unexpected_identity",
     "legendFormat": "UnexpectedHandshakeIdentity"
    },
    {
     "expr": "reth_network_disconnect_requested",
     "legendFormat": "DisconnectRequested"
    },
    {
     "expr": "reth_network_null_node_identity",
     "legendFormat": "NullNodeIdentity"
    },
    {
     "expr": "reth_network_tcp_subsystem_error",
     "legendFormat": "TCPSubsystemError"
    },
    { "expr": "reth_network_incompatible", "legendFormat": "IncompatibleP2PVersion" },
    { "expr": "reth_network_protocol_breach", "legendFormat": "ProtocolBreach" },
    { "expr": "reth_network_too_many_peers", "legendFormat": "TooManyPeers" }
   ]
  },
  { "title": "Downloader: Headers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_total_downloaded",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_headers_total_flushed",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_downloaded[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_flushed[$__rate_interval])",
     "legendFormat": "Flushed/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the header downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_timeout_errors",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "reth_downloaders_headers_unexpected_errors",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "reth_downloaders_headers_validation_errors",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for headers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_in_flight_requests",
     "legendFormat": "In flight requests"
    },
    { "expr": "reth_network_connected_peers", "legendFormat": "Connected peers" }
   ]
  },
  { "title": "Downloader: Bodies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "I/O",
   "type": "timeseries",
   "description": "The internal state of the headers downloader: the number of downloaded headers, and the number of headers sent to the header stage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_total_downloaded",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_bodies_total_flushed",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_flushed[$__rate_interval])",
     "legendFormat": "Flushed/s"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_downloaded[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_responses",
     "legendFormat": "Buffered responses"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks",
     "legendFormat": "Buffered blocks"
    },
    {
     "expr": "reth_downloaders_bodies_queued_blocks",
     "legendFormat": "Queued blocks"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the bodies downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_timeout_errors",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "reth_downloaders_bodies_unexpected_errors",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "reth_downloaders_bodies_validation_errors",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for bodies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_in_flight_requests",
     "legendFormat": "In flight requests"
    },
    { "expr": "reth_network_connected_peers", "legendFormat": "Connected peers" }
   ]
  },
  {
   "title": "Downloader buffer",
   "type": "timeseries",
   "description": "The number of blocks and size in bytes of those blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_buffered_blocks_size_bytes",
     "legendFormat": "Buffered blocks size (bytes)"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Payload Builder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Jobs",
     "type": "timeseries",
     "description": "Number of active jobs",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "targets": [
      { "expr": "reth_payloads_active_jobs", "legendFormat": "Active Jobs" }
     ]
    },
    {
     "title": "Initiated Jobs",
     "type": "timeseries",
     "description": "Total number of initiated jobs",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
     "targets": [
      { "expr": "reth_payloads_initiated_jobs", "legendFormat": "Initiated Jobs" }
     ]
    },
    {
     "title": "Failed Jobs",
     "type": "timeseries",
     "description": "Total number of failed jobs",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
     "targets": [
      { "expr": "reth_payloads_failed_jobs", "legendFormat": "Failed Jobs" }
     ]
    }
   ]
  }
 ]
}